-- AlterTable
ALTER TABLE "Habit" 
ADD COLUMN "frequency" VARCHAR(255) NOT NULL DEFAULT 'daily',
ADD COLUMN "target" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "icon" TEXT,
ADD COLUMN "color" TEXT,
ADD COLUMN "archived" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "endDate" TIMESTAMP(3),
ADD COLUMN "category" TEXT,
ADD COLUMN "priority" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "HabitRecord" 
ADD COLUMN "value" DOUBLE PRECISION,
ADD COLUMN "notes" TEXT,
ADD COLUMN "mood" INTEGER,
ADD COLUMN "difficulty" INTEGER,
ADD COLUMN "skipped" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE INDEX "HabitRecord_habitId_date_idx" ON "HabitRecord"("habitId", "date"); 